### ISSUE TITLE
Which Guitar for Beginners?

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/learn-music#32]
I have played guitar at various points in my life but I still consider myself a "beginner" ...
I don't currently _own_ a guitar because I _gave_ mine away to my cousin when I went to University wanted to focus on my studies. He didn't _touch_ it so I should just ask for it back. But it's _easier_ to just get a new one. (_don't ask_ ... 🙄)

This is a good video comparing the sound of Nylon and Steel string acoustic guitars:
[![image](https://user-images.githubusercontent.com/194400/85930593-aaa8c500-b8b5-11ea-8441-55cef50b0204.png)](https://youtu.be/JL4w3ixUDdw)
https://youtu.be/JL4w3ixUDdw
I prefer the _sound_ of the Nylon but the _versatility_ of the Steel string.

7 Acoustic Guitar Body Shapes, Their Differences and Sounds:
[![image](https://user-images.githubusercontent.com/194400/85930649-07a47b00-b8b6-11ea-9647-23a04d9c41b3.png)](https://youtu.be/F9TZwTtXYSY)
https://youtu.be/F9TZwTtXYSY

There is _definitely_ too much choice! 🙄 

I think the easiest thing is to simply guide oneself by _budget_ and then filter for the types of guitars you can _afford_.
I'm not looking to spend very much but I also don't want a piece of junk that I will constantly need to retune. 

Epiphone PRO-1 NA Natural - this guitar is _designed_ to be easy to play by beginners.
https://www.musicstore.com/en_PT/EUR/Epiphone-PRO-1-NA-Natural/art-GIT0038933-000
![image](https://user-images.githubusercontent.com/194400/85930978-86021c80-b8b8-11ea-97fb-6d96ac45b7bb.png)
 
Watch the intro video to get a good idea of the characteristics of this instrument: 

Epiphone PR-4E Player Pack - this is obviously made to a price, but it's great that it comes with an Amp and a Case!
https://www.musicstore.com/en_PT/EUR/Epiphone-PR-4E-Player-Pack/art-GIT0035583-000
![image](https://user-images.githubusercontent.com/194400/85931001-b6e25180-b8b8-11ea-9eb3-0065e7429f7e.png)

[![image](https://user-images.githubusercontent.com/194400/85931287-248f7d00-b8bb-11ea-83ec-20d7d93cda84.png)](https://youtu.be/zyZZuyy73kU)
https://youtu.be/zyZZuyy73kU

Fender FA-125CE NAT
https://www.egitana.pt/fender-fa-125ce-nat
![image](https://user-images.githubusercontent.com/194400/85931118-d168fa80-b8b9-11ea-9653-2391b026b6d7.png)

This model is available at our _local_ music store: https://www.salaomozart.com/product/885978936496
![image](https://user-images.githubusercontent.com/194400/85931040-13457100-b8b9-11ea-8ef3-0814b3dadb26.png)
I obvs prefer to buy from a _local_ seller as it means the VAT is kept in PT and provides _local_ employment.

The local shop doesn't have anything less than €100 ($112 USD at time of writing)
https://www.salaomozart.com/shop/instrumentos-musicais-1/guitarras-e-baixos/guitarra-eletroacustica#
![image](https://user-images.githubusercontent.com/194400/85932432-08440e00-b8c4-11ea-8bd3-5bca99f66519.png)

I'm OK with spending the €155 on the Fender or even more on something else if the _sound_ is noticeably better and/or it's easier for beginners to get started with playing. 💭 

I will treat myself to a new instrument once I've _finished_ building the _first_ Kitchen @home https://github.com/dwyl/home/issues/54
I don't want to get distracted with practicing for hours while there is still "blocker" work to be done.

**Comment by nelsonic** [comment]
This Yamaha F310P2WS pack is a good option too:
https://www.musicstore.com/en_PT/EUR/Yamaha-F310P2WS-Acoustic-Guitar-Pack-Natural-/art-GIT0027341-000
![image](https://user-images.githubusercontent.com/194400/85932623-87861180-b8c5-11ea-849f-c9a6c8757a5b.png)

I like the idea of having a ***stand*** so that there is less inertia to play. 💭 
Sadly this guitar (Pack) is not available anywhere in PT (_that I can find_) ...
And I don't really want to pay €30 shipping cost unnecessarily ... (_shipping is free over €200_)
I might as well get the Fender (_above_) and spend the shipping money on a stand.

**Comment by nelsonic** [comment]
This pack is **dope**:
https://www.musicstore.com/en_PT/EUR/Epiphone-Slash-AFD-Les-Paul-Special-II-Performance/art-GIT0030927-000
![image](https://user-images.githubusercontent.com/194400/86263052-936d1e80-bbb8-11ea-9d90-599c430e5325.png)

The biggest advantage of a solid body Electric Guitar is being able to practice _quietly_:

[![image](https://user-images.githubusercontent.com/194400/86263703-7e44bf80-bbb9-11ea-8cc9-7101de10a324.png)](https://youtu.be/Shd2wQSi4RI)

i.e. you either don't plug it in and the noise level is comparatively low 
or you plug in to the Amp but use *headphones* to listen to the sound.

Something to consider ... 💭

**Comment by nelsonic** [comment]
Comparison of the two Epiphone guitars I’m considering: https://youtu.be/vOLee5dYmuM

**Comment by nelsonic** [comment]
[![image](https://user-images.githubusercontent.com/194400/86268220-c1099600-bbbf-11ea-9779-fc4e3c3f7156.png)](https://youtu.be/pEOnUxj9Esg)

People who claim to be able to tell the difference in a blind test 
are either audiophiles, studio sound engineers or _lying_ to you. 

Also ... if this *Rainbow* one wasn't _double_ the price ... 💭 
https://www.amazon.co.uk/Epiphone-Paul-Tribute-Prizm-Outfit/dp/B07JQMVMZ2
![image](https://user-images.githubusercontent.com/194400/86268871-c74c4200-bbc0-11ea-8dae-61f9c10da79c.png)

**Comment by nelsonic** [comment]
In this "Epiphone vs. Gibson Les Paul Blindfold Challenge", 
Rob "Chappers" Chapman (of Chapman Guitars) mistakes an Epiphone for a Gibson:
[![image](https://user-images.githubusercontent.com/194400/86334609-5d29b080-bc45-11ea-8f36-ffa881c00f38.png)](https://youtu.be/aGTvjbbVl-o?t=448)
https://youtu.be/aGTvjbbVl-o?t=448
And at 11 mins he says of the Gibson "this feels like an Epiphone to me". 

![image](https://user-images.githubusercontent.com/194400/86336175-687ddb80-bc47-11ea-8ab0-3013d691bc13.png)

Again, anyone who _thinks_ they can tell them apart in a _blind_ test is lying. 
There are so many variables in what makes the _sound_ of an Electric guitar 
that it's _really_ difficult to tell the difference. 

The Epiphone Les Paul Classic is closest to a "real" Les Paul:
https://www.musicstore.com/en_PT/EUR/Epiphone-Les-Paul-Classic-Heritage-Cherry-Sunburst/art-GIT0051923-000
![image](https://user-images.githubusercontent.com/194400/86347295-04164880-bc56-11ea-9b43-8f344ec8cecb.png)

This _feels_ like a lot of money to pay for a _hobby_ ... 💭

**Comment by nelsonic** [comment]
After _much_ research, I've come to understand that the best _value-for-money_ beginner _electric_ guitar is 
Epiphone Les Paul Studio LT which costs **€199**:
https://www.musicstore.com/en_PT/EUR/Epiphone-Les-Paul-Studio-LT-Heritage-Cherry-Sunburst-/art-GIT0042551-000
![image](https://user-images.githubusercontent.com/194400/86348612-cca89b80-bc57-11ea-9fae-cc9e45efa74e.png)


[![image](https://user-images.githubusercontent.com/194400/86348669-dfbb6b80-bc57-11ea-8bf0-5a94c2b5816d.png)](https://youtu.be/n6dgJ2wT3Kc)
https://youtu.be/n6dgJ2wT3Kc

_Obviously_ there are some "haters" on the video as there are with _any_ YT video. Haters gonna hate. 
But This guitar is both easy to play and sounds decent. The pickups are slightly cheaper, but they still sound good to my ears (I'm listening with ["studio monitor"](https://github.com/dwyl/studio/issues/10) headphones). 🎧

**Comment by nelsonic** [comment]
This is _definitely_ not a "beginner" guitar. But it's a _comparatively_ reasonably priced Gibson:
https://www.ebay.co.uk/itm/Gibson-Les-Paul-Studio-fireburst-and-HARD-CASE/233626219745
![image](https://user-images.githubusercontent.com/194400/86352351-9241fd00-bc5d-11ea-955a-3c4efca00cb3.png)

**Comment by nelsonic** [comment]
Still really like the look of the Epiphone Les Paul Standard Plus Pro:
https://www.thomann.de/gb/epiphone_les_paul_standard_plus_pro_dl.htm
![C723FECA-E60D-4615-BEFC-303E2760240E](https://user-images.githubusercontent.com/194400/86843057-f1f53980-c09d-11ea-81b1-bd80133e8aa0.png)

**Comment by nelsonic** [comment]
Yesterday after work, we went to the guitar store and I tried a few guitars. 
Didn't like the _feel_ of the Gibson Les Paul. The edge of the body was sharp and cut into my right arm and the neck seemed too short. The ergonomics felt "*off*". Maybe I will reconsider it in the future once I've relearned how to play and can appreciate it's form-factor. But for now I'm definitely not getting one. 

I _much_ prefer the ergonomics on the Strat and I feel that it's _way_ more beginner friendly. 🎸

After watching a few videos on the  **Yamaha SLG200N** (aka "Silent Guitar") I'm convinced that the combination of low noise while practicing and *superb* sound when amplified is a winner.
Obviously it's not "cheap" at €600, which is more than the second hand Gibson Les Paul I was considering before I tried it in the shop ... But I feel this is a _good_ investment if I'm going to re-learn and enjoy playing guitar.

**Comment by nelsonic** [comment]
https://www.musicstore.com/en_PT/EUR/search?SearchTerm=Yamaha+silent+guitar
![A91A7FFE-14CE-4805-A8DF-9CBF920BDC65](https://user-images.githubusercontent.com/194400/87218003-ea0bf280-c346-11ea-9eea-438ad7d20b65.png)

https://www.musicstore.com/en_PT/EUR/Yamaha-Silent-Guitar-SLG-200-NW-Natural-Nylon/art-GIT0041064-000

![A05D5A7B-A957-4C19-9C59-DC86577BDE58](https://user-images.githubusercontent.com/194400/87218096-99e16000-c347-11ea-8e71-e90c712c5699.png)


The Yamaha SLG200 is **_more_ expensive** than a MIM Fender Strat: https://www.musicstore.com/en_PT/EUR/Fender-Player-Series-Stratocaster-MN-BLK/art-GIT0045987-000

![285B42F9-8EFD-4B3E-A39D-B5809A41B7BE](https://user-images.githubusercontent.com/194400/87218229-b7fb9000-c348-11ea-85e8-e649d6a50d5e.png)


I genuinely prefer the ***sound*** of an accoustic guitar and think I will enjoy _playing_ and recording with it more.

**Comment by nelsonic** [comment]
https://m.olx.pt/anuncio/yamaha-silent-slg200s-c-garantia-oportunidade-IDFM1gt.html
![9217FCE1-D049-454D-9BF5-C732145BAD13](https://user-images.githubusercontent.com/194400/87218503-453fe400-c34b-11ea-8a99-1b3f57b96293.png)

Sent message asking if they still have it. 🤞

**Comment by nelsonic** [comment]
Anatomy of an Acoustic Guitar: https://theacousticguitarist.com/anatomy-of-an-acoustic-guitar
![image](https://user-images.githubusercontent.com/194400/87229846-806e0180-c3a3-11ea-979b-25e7a9ff7ba2.png)

**Comment by nelsonic** [comment]
This video shows how quiet the Yamaha SLG200S Silent Guitar is when not plugged in to an Amplifier:
[![image](https://user-images.githubusercontent.com/194400/87230905-c7abc080-c3aa-11ea-8b6a-e668abbc90d1.png)](https://youtu.be/j2z0NRz6caU)
https://youtu.be/j2z0NRz6caU

It's _obviously **not**_ "_silent_". It makes a similar level of noise to an electric guitar 
but it has a wider neck nut which makes easier to play and the sound is really good.

**Comment by nelsonic** [comment]
This Ibanez V50NJP-NT Jam Pack is very good value for money:
https://www.musicstore.com/en_PT/EUR/Ibanez-Jampack-VC50NJP-NT-Natural/art-GIT0026847-000V000151709
![image](https://user-images.githubusercontent.com/194400/87311844-b46a3380-c517-11ea-8195-7e43a0c6e596.png)


Cheaper at our local Music shop: https://www.salaomozart.com/product/ibanez-v50njp-nt-jam-pack
![image](https://user-images.githubusercontent.com/194400/87311704-81c03b00-c517-11ea-9cfb-48c19ad5d5ee.png)

**Comment by nelsonic** [comment]
After a _lot_ of research into the Yamaha Silent Guitars: https://github.com/nelsonic/learn-music/issues/32#issuecomment-656998318 ⬆️  
(_I watched 20+ videos and read 10 forum threads on it on Saturday night when I couldn't sleep ...!_)

https://europe.yamaha.com/en/products/musical_instruments/guitars_basses/silent_guitar/slg200_series
![image](https://user-images.githubusercontent.com/194400/87343797-55bbae80-c545-11ea-88fe-5c589f8d1154.png)

Brief overview: https://youtu.be/9GKHr3lWb3g
[![image](https://user-images.githubusercontent.com/194400/87345652-47bb5d00-c548-11ea-9ddc-dbe88da18320.png)](https://youtu.be/9GKHr3lWb3g)

_Extended_ product intro: https://youtu.be/kANP9OgwpMY
[![image](https://user-images.githubusercontent.com/194400/87346625-cebd0500-c549-11ea-827a-2cc899725b90.png)](https://youtu.be/kANP9OgwpMY)


Professional Musician review: https://youtu.be/N8rcyfbQ1Vo
[![image](https://user-images.githubusercontent.com/194400/87345549-222e5380-c548-11ea-9bda-0d4be6a7ec85.png)](https://youtu.be/N8rcyfbQ1Vo)

Cesar is a professional touring/session musician who has **_many_ guitars** and he _swears_ by the SLG200S for practice, live performance and _recording_. Watch this comparison video he made: https://youtu.be/9xp8tZMkxQs

[![image](https://user-images.githubusercontent.com/194400/87346810-104db000-c54a-11ea-81b8-628dfb34b4a4.png)](https://youtu.be/9xp8tZMkxQs)


In this video, Aaron Short explains why the https://youtu.be/im3-50drfbY
[![image](https://user-images.githubusercontent.com/194400/87353288-61fb3800-c554-11ea-83de-1f501dae1cb4.png)](https://youtu.be/im3-50drfbY)

The video has a few dislikes/comments from people who _really_ don't _get_ it! 🤦 
_Obviously_ a "real" acoustic guitar sounds better because the sound is "real".
But for my requirements, **low noise**, this guitar is absolutely ***purrrrfect***! 

![image](https://user-images.githubusercontent.com/194400/87353591-041b2000-c555-11ea-850e-1dffb5fa9ba7.png)


# `tl;dr`

I bought a **_second hand_ Yamaha SLG200s** with a 2 year warranty (_I got all the paperwork transferred over_). 
It was purchased on on 5th May 2020 for €610 by a chap who apparently didn't _like_ the sound:

![image](https://user-images.githubusercontent.com/194400/87344735-d8913900-c546-11ea-8189-906b868ac631.png)

He wanted to get rid of it so he sold it for **€450** (26% discount). It doesn't have a single scratch on it. 
In the process met [Luthier](https://en.wikipedia.org/wiki/Luthier)  [Marcelo Gatti](https://forumusica.com/servicos/tecnicos-e-luthiers/mgatti-luthieria-setup-repara%C3%A7%C3%A3o-manuten%C3%A7%C3%A3o-e-modifica%C3%A7%C3%B5es-em-instrumentos-fretted-r368/) who is an absolute gem of a person!

https://www.olx.pt/anuncio/yamaha-silent-slg200s-c-garantia-oportunidade-IDFM1gt.html
![image](https://user-images.githubusercontent.com/194400/87341870-37a07f00-c542-11ea-81a5-059c74b7d884.png)

€610 is the price in most _online_ shops. Music Store has them for €609 https://github.com/nelsonic/learn-music/issues/32#issuecomment-657001254 (above)
https://www.musicstore.com/pt_PT/EUR/Yamaha-Silent-Guitar-SLG-200-S-Natural-Steel-Strings/art-GIT0035754-000

While this is _definitely_ (quite a lot more) than I _wanted_ to spend on a guitar, 💸 
I've been playing it this evening and it sounds _fantastic_!! 😍 
And by that I mean it's _lack_ of noise is _amazing_! 🔇 
I've been playing a few (_very basic_) songs with headphones plugged in and it's _amazing_!!
100% no regrets spending a bit more money on this guitar. 

Now I need to buy a **wall mount**  to hang it within easy reach. #36

**Comment by nelsonic** [comment]
While I was at Marcelo's shop on Saturday, he had _this_ exact **Epiphone Les Paul Standard** (Pro) with ProBucker pickups, LockTone Tune-o-Matic bridge + stop bar and Grover Rotomatics tuners.

https://migueldelgadoesilva.olx.pt/anuncio/epiphone-les-paul-standard-IDFKfYm.html
![image](https://user-images.githubusercontent.com/194400/87355222-e9967600-c557-11ea-9a25-e7cb0f0ed286.png)

It has a few scratches on the headstock:
![image](https://user-images.githubusercontent.com/194400/87357036-1c8e3900-c55b-11ea-9a66-be12f75b01c4.png)

a few _minor_ marks on the body:
![image](https://user-images.githubusercontent.com/194400/87357076-30399f80-c55b-11ea-801d-0b536e585ca1.png)

and one _burn_ mark on the _top_ from where someone has _clearly_ rested a cigarette on it: 🤦 
![image](https://user-images.githubusercontent.com/194400/87357173-595a3000-c55b-11ea-94b3-b0dd5a39abb3.png)

The photo is taken under bright (harsh) lighting so the burn appears _much_ worse than it is IRL!
I held it up-close and the mark is barely noticeable unless you go _searching_ for it!


![epiphone-lespaul-standard-pro](https://user-images.githubusercontent.com/194400/87357505-0765da00-c55c-11ea-9655-3c4bc9603544.jpeg)

His "cash" price was **€280** which is absurdly cheap for this instrument!


For reference the Epiphone Les Paul Standard Pro is the top of the range in the Epiphone lineup:

https://www.musicstore.com/en_PT/EUR/Epiphone-Les-Paul-Standard-60s-Bourbon-Burst/art-GIT0051912-000
![image](https://user-images.githubusercontent.com/194400/87356295-c076e500-c559-11ea-952f-e869c3026183.png)

![image](https://user-images.githubusercontent.com/194400/87356388-e3a19480-c559-11ea-87ff-897a0bd0ccaf.png)

Just the tuner machine heads on this guitar cost £80
https://www.thomann.de/gb/grover_gr10218c_rotomatics.htm
![image](https://user-images.githubusercontent.com/194400/87356617-41ce7780-c55a-11ea-82f7-a100c2710857.png)

The Probucker pickups retail for $169: https://www.epiphone.com/Gear/Pickups-and-Electronics/IEPB
![image](https://user-images.githubusercontent.com/194400/87356692-675b8100-c55a-11ea-9c2c-5fb0cdb7e4bd.png)

I could strip this guitar down and sell it for _parts_ and make more money than he is asking for it!! 🤯

**Comment by nelsonic** [comment]
This is a _bargain_ price for the Fender FA-125 Dreadnought WN Sunburst
https://www.egitana.pt/fender-fa-125-dreadnought-wn-sunburst
![image](https://user-images.githubusercontent.com/194400/87359070-03878700-c55f-11ea-9b59-42d897055c1d.png)

Going to stick with the SLG200S for now.

**Comment by nelsonic** [comment]
https://www.masterclass.com/articles/best-beginner-guitars-for-new-guitar-players#what-types-of-electric-guitars-are-there
![image](https://user-images.githubusercontent.com/194400/87666915-634d8000-c761-11ea-9e59-5a2fb0e7fc63.png)

**Comment by nelsonic** [comment]
Dagan’s review of the SLG200 (published 2 weeks after I got it) “_this thing is **amazing** to play_”: https://youtu.be/jTpCoJDsE_M

**Comment by nelsonic** [comment]
Considering: [Fender CD-140SCE V2 Natural](https://www.salaomozart.com/product/fender-cd-140sce-natural)
https://www.salaomozart.com/product/fender-cd-140sce-natural
<img width="1360" alt="image" src="https://github.com/nelsonic/learn-music/assets/194400/031eb7a3-7919-480a-8600-0abfb022bc65">

as a gift for co-owner of `Gerês` to leave there for when they visit and want to practice. 🎸

**Comment by iteles** [comment]
If you gift a guitar to this person it will Not be left in Gerês. You can't attach a location clause to a mobile gift someone is actually interested in having in their home where they can use it more than 3 or 4 times a year 😅

If you want to have a guitar in Gerês then we take one and leave it there but it will not be a gift to anyone, it'll be us leaving something there. Which is fine. But seems like a waste to have such an expensive guitar there - it will get wrecked by other people without a doubt. 
There should be a cheaper, easily replaceable guitar there. And if you want to own this fender, just buy it for our home 👌🏻

**Comment by nelsonic** [comment]
@iteles thank you for your interest in this topic. 🎉 
Indeed ... with a **hard case** it's a _very_ portable "mobile gift". 🚗 
And I have no intention of making the location "_conditional_". 
But I did get a green light from the _other_ co-owner 🟢 
to put a **wall-mount** in Gerês so there will be a _place_ for it. ✅ 
The point is this: the person doesn't have _time_ to practice the guitar ⏳ 
in their "normal" place of residence. But on "holiday" they `do` have time. 👌 

Perhaps I _should_ have just written:
researching a _good_ guitar to buy with the profits a recent investment windfall. 📈 💰 
and not said _who_ it was for. 👌

**Comment by iteles** [comment]
I just wanted you to be aware of the wording. If you present it as a gift for a specific person who has handed in her notice and will be retiring and have nothing to do from September onwards, it will not stay in Gerês 👌🏻

**Comment by nelsonic** [comment]
The guitar I would like to get for _myself_ is ***`10x`*** the price of this already **_very_ good `Fender`**. 
https://www.musicstore.com/pt_PT/EUR/Gibson-Songwriter-2019-CE-Antique-Natural-/art-GIT0046989-000
<img width="1172" alt="image" src="https://github.com/nelsonic/learn-music/assets/194400/5e093ba6-8b40-4197-a3e3-fa652b2d76b9">

"DEAL!" indeed ... 🤣 
Within the "higher end" acoustic guitars this Songwriter is a _deal_!

<img width="1197" alt="image" src="https://github.com/nelsonic/learn-music/assets/194400/84cb8ba7-361e-4682-9e13-c0c55ea3d9bd">

It's _widely_ regarded as a "perfect" guitar. 😍 

But ... I'm _definitely not_ spending this kind of money on a **guitar** in the near future!! ⏳ 
Instead I'm conserving _all_ of my capital for a [_much_ bigger prise](https://github.com/dwyl/phase-three/issues/116)!
